from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Any


def _value(payload: dict[str, Any], *keys: str, default: Any = None) -> Any:
    current: Any = payload
    for key in keys:
        if not isinstance(current, dict):
            return default
        current = current.get(key)
    return default if current is None else current


def render_stage0_report(baseline: dict[str, Any]) -> str:
    release = baseline.get("release", {})
    runtime = baseline.get("runtime", {})
    mods = baseline.get("mods", {})
    mcp_probe = baseline.get("mcp_probe", {})
    static_hints = baseline.get("static_hints", {})
    release_info = release.get("release_info", {}) if isinstance(release.get("release_info"), dict) else {}
    runtime_config = runtime.get("runtime_config", {}) if isinstance(runtime.get("runtime_config"), dict) else {}
    required_files = runtime.get("required_files", {}) if isinstance(runtime.get("required_files"), dict) else {}
    sts2_mcp = mods.get("sts2_mcp", {}) if isinstance(mods.get("sts2_mcp"), dict) else {}

    lines = [
        "# Stage 0 Baseline Report",
        "",
        f"Generated at: `{datetime.now(timezone.utc).isoformat()}`",
        "",
        "## Game",
        "",
        f"- Game directory: `{release.get('game_dir')}`",
        f"- Directory exists: `{release.get('exists')}`",
        f"- Steam app ID: `{release.get('steam_appid')}`",
        f"- Version: `{release_info.get('version')}`",
        f"- Commit: `{release_info.get('commit')}`",
        f"- Branch: `{release_info.get('branch')}`",
        f"- Date: `{release_info.get('date')}`",
        f"- Main assembly hash: `{release_info.get('main_assembly_hash')}`",
        "",
        "## Runtime",
        "",
        f"- Data directory: `{runtime.get('data_dir')}`",
        f"- Target framework: `{_value(runtime_config, 'runtimeOptions', 'tfm')}`",
        f"- Included frameworks: `{_value(runtime_config, 'runtimeOptions', 'includedFrameworks', default=[])}`",
        "",
        "### Required files",
        "",
    ]
    for name, info in required_files.items():
        lines.append(f"- `{name}`: exists=`{info.get('exists')}` path=`{info.get('path')}`")

    lines.extend(["", "### Dependency versions", ""])
    for name, version in sorted((runtime.get("dependency_versions") or {}).items()):
        lines.append(f"- `{name}`: `{version}`")

    lines.extend([
        "",
        "## STS2_MCP",
        "",
        f"- DLL exists: `{sts2_mcp.get('dll_exists')}`",
        f"- Config path: `{sts2_mcp.get('conf_path')}`",
        f"- Manifest path: `{sts2_mcp.get('manifest_path')}`",
        f"- Config: `{sts2_mcp.get('conf')}`",
        f"- Manifest: `{sts2_mcp.get('manifest')}`",
        f"- Probe: host=`{mcp_probe.get('host')}` port=`{mcp_probe.get('port')}` status=`{mcp_probe.get('status')}`",
    ])
    if mcp_probe.get("error"):
        lines.append(f"- Probe error: `{mcp_probe.get('error')}`")

    lines.extend(["", "## Installed mods", ""])
    for mod in mods.get("mods", []):
        manifests = mod.get("manifests") or []
        manifest_names = [Path(item.get("path", "")).name for item in manifests]
        lines.append(
            f"- `{mod.get('name')}` layout=`{mod.get('layout')}` dlls=`{mod.get('dlls')}` "
            f"pcks=`{mod.get('pcks')}` manifests=`{manifest_names}` affects_gameplay=`{mod.get('affects_gameplay')}`"
        )

    lines.extend([
        "",
        "## Static patch-point hints",
        "",
        "These entries are not accepted patch points. They are unvalidated strings extracted from `sts2.dll` and must be verified with STS2_MCP or a decompiler before Stage 1.",
        "",
        f"- Assembly: `{static_hints.get('assembly')}`",
        f"- Assembly exists: `{static_hints.get('assembly_exists')}`",
        "",
    ])
    for group in static_hints.get("candidate_groups", []):
        lines.extend([
            f"### {group.get('area')}",
            "",
            f"- Source: `{group.get('source')}`",
            f"- Status: `{group.get('status')}`",
            "- Hints:",
        ])
        for hint in group.get("hints", [])[:25]:
            safe_hint = str(hint).replace("`", "'")
            lines.append(f"  - `{safe_hint}`")
        lines.append("")

    lines.extend([
        "## Stage 0 acceptance status",
        "",
        "- Environment baseline: generated by this report.",
        "- STS2_MCP config: recorded above.",
        "- STS2_MCP live probe: see probe status above; if `not_reachable`, launch the game with STS2_MCP loaded and rerun `probe-mcp` or `write-report`.",
        "- Patch points: static hints are not sufficient. Fill `docs/stage0/PATCH_POINT_DISCOVERY.md` after runtime/decompiler validation.",
        "",
    ])
    return "\n".join(lines)


def write_stage0_report(path: Path, baseline: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_stage0_report(baseline), encoding="utf-8")
